server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: mall-mng

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mall.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
